### ISSUE TITLE
Issue with CMakeAutoGen when importing main project with add_subdirectory

### ISSUE THREAD

**Issue by evpobr** [madebr/CMakeAutoGen#2]
See https://github.com/erikd/libsndfile/pull/242

Some example project `SndFileTest` imports `libsndfile` with `add_subdirectory` from `libsndfile` subdirectory. Build directory is `CMakeBuild`. 

Generated output should be placed in

       SndFileTest/CMakeBuild/libsndfile/src
       SndFileTest/CMakeBuild/libsndfile/tests

But it is placed in:

       SndFileTest/CMakeBuild/src
       SndFileTest/CMakeBuild/tests

Can you help me? Working branch is https://github.com/erikd/libsndfile/tree/bugfix/cmake-out-of-source.

Test project:

[SndFileTest.zip](https://github.com/madebr/CMakeAutoGen/files/955180/SndFileTest.zip)

**Comment by madebr** [comment]
Not actually a bug with CMakeAutoGen but with the wrapper.
Also written by me.
Doh!

I fixed it in https://github.com/madebr/libsndfile/tree/out_of_source

**Comment by evpobr** [comment]
Thanks, it works.
